# Site settings
title: Nicholas Pope - The Most Hospitable Developer
email: pope410211@gmail.com
description:
phone: 623-340-2499

url: "pope410211.github.io"
twitter_username: pope410211
github_username:  pope410211

# Markdown library
markdown:   Redcarpet

# Author details.
Nick_Pope:
    name: Nick Pope
    email: pope410211@gmail.com
    web: http://twitter.com/pope410211
